# Generated by Django 2.0.1 on 2018-02-22 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSample',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('finish_time', models.DateTimeField(blank=True, null=True)),
                ('submission', models.BinaryField(blank=True, null=True)),
                ('submission_file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('applicant_name', models.CharField(max_length=255)),
                ('applicant_email', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkSampleTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.CharField(help_text='What role is this for?', max_length=255)),
                ('welcome_message', models.TextField(help_text='The first page that is displayed. HTML is allowed.')),
                ('instructions', models.TextField(help_text='The work sample instructions. HTML is allowed.')),
                ('final_message', models.TextField(help_text='The page that appears after submitting. HTML is allowed.')),
                ('allowed_minutes', models.IntegerField()),
                ('email_recipients', models.TextField(help_text='Multiple email addresses can be entered. Separate addresses using a comma')),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='worksample',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.WorkSampleTemplate'),
        ),
    ]
